services:
  bartenderly:
    container_name: bartenderly
    build: spr
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_user
      POSTGRES_DB: dev
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
